name: CI - Build & Test Flask Docker App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t flask-api .

    - name: Run container
      run: |
        docker run -d -p 5000:5000 --name test-container flask-api
        sleep 5

    - name: Test API
      run: |
        curl --fail http://localhost:5000 || (docker logs test-container && exit 1)

    - name: Cleanup
      run: docker rm -f test-container
